services:
  web:
    build: ./web
    container_name: todo_web
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rodo_db
    volumes:
      - ./web:/app
    expose:
      - "5000"

db:
  image: postgres:15
  container_name: todo_db
  restart: always
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTEGRES_DB: todo_db
  volumes:
    - pgdata:/var/lib/postgresql/data
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

nginx:
  image: neginx:latest
  container_name: todo_nginx
  restart: always
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
    - web

volumes:
  pgdata:
